### ISSUE TITLE
Spike using Virtual DOM instead of our own implementation.

### ISSUE THREAD

**Issue by treshugart** [skatejs/kickflip#1]
It'd be nice to not have to maintain our own implementation, so we should spike using [Virtual DOM](https://github.com/Matt-Esch/virtual-dom) as the defacto diff / patch implementation for this.

However, there are some advantages to our implementation we should consider:
1. It's smaller.
2. It can diff real DOM and virtual DOM interchangeably.
3. On initial investigation it seems smarter about attribute / property setting.
4. Does Virtual DOM bind events?

Number 2 and 4 are a must and we can probably work around number 3. Number 1 isn't very important as it's not that much smaller (30k unmin or so).

The biggest priority is ensuring that we can still do `element.appendChild(node)` and not lose a reference to `node` during the rendering process. Maybe due to the nature of the patching process and doing as little transformations as possible, this is not possible. Need to investigate.

**Comment by matthewrobb** [comment]
Have you considered using https://github.com/google/incremental-dom

**Comment by treshugart** [comment]
Thanks @matthewrobb, I have not, though I have heard of it. It seems to have matured quite a bit since the last time I checked it out. I'll give it a go in the next week and see if it will work.

**Comment by treshugart** [comment]
Decided to use Incremental DOM instead. See #2.
