### ISSUE TITLE
The kickflip() custom element name should be optional.

### ISSUE THREAD

**Issue by treshugart** [skatejs/kickflip#4]
If it is optional, `kickflip()` should return a function that accepts a name which will return a constructor.

This should still be supported:

``` js
const MyElement = kickflip('my-element', {
  render () {}
});
```

However we should support this:

``` js
const defineMyElement = kickflip({
  render () {}
});

const MyElement = defineMyElement('alternate-name');
```

**Comment by seancurtis** [comment]
Looks good. Will this mean we can create 2 elements using the same base, but override/extend one of them without affecting the other?

**Comment by treshugart** [comment]
@seancurtis 

> Looks good. Will this mean we can create 2 elements using the same base, but override/extend one of them without affecting the other?

Yep. Basically, it becomes a factory to create a specific type of element.

**Comment by treshugart** [comment]
This may actually be better going into Skate?

**Comment by treshugart** [comment]
Closing as this should be implemented in Skate proper.
